language: ruby
cache:
- bundler
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rails assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: fojpEmYtG/tBihjKplepzfkhCphUd24ozHrj6+pHCWG5k/WXGo4OzvukYzxtqP3yPgZUvAzBFa+lIHwYpnO/RvS1qprd3ghpl+Da3gm5Lb6y6TPtlu/ermjPY6EAdPEXKoEL84Kh+9lvcpqaPhpmr/I+q2kn+3y4L3pLyci+FgGlt4kMxLIhwyKAMJuRL+XWlwDeDIqv9+IA6932Z/ubkUEBL4+j8mh1J2gt8Y+Fj2a1sksIaQev0oOYvleXp5Vw6fnQJzwNaqToN9q9MV6z72BIixIPMDtMtbHCEy15piW2F5EtpZyw7NM504OtSMjhiZkMbMJ/7w2W6mhPg0ldn497CYWvRjDNA/tOW52p3RrMd3wHGoPrKQGlVr3DRIq6itT14/mYJ7vCJfhFpo17288fE6Qp3L6S5A3HThUylnihx6puoOAdRfqJmr//StdKH3vgjF6Cua3lyQvE80k4mxEn6KN4RSUI8EzjJhgKngvxi6WWv3NZmFd8Zzk1y0bQ05yMgSWnM2Vi6qhp6F8/uvxTQAfB5f/fHVXPCkmlycsb9nqPrs6uyzfnohr3NrSRHRs8Wop2TDeGisy9Z81VB5YSupCaEdcNv15DJezqs7vruIIMCWqvORwQsEzZj3Gw+vTTCVFZsbOyVh7obvbxKURjhq0iNwOXCm1LSWnOUDg=
  run:
  - heroku run rake db:create RAILS_ENV=production
  - heroku run rake db:migrate RAILS_ENV=production
  - heroku run rake assets:precompile
  app: rushabhsales
  on:
    repo: shalinbhatt/rushabhsales
