language: ruby
cache:
- bundler
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rails assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: m5s9qWnN07nXWvUEaDLJCBjr7/m7B3R4NFd3fOu5W48gOpDiMUMwJ3gfBX0CnCzMkgv5fD3xjluRoagg2CorYNFmy2+VjaCenmcZwP9ekq6Xn7Ey1o0XqJO865rrIyb3l/9I/4W4m10Vtn6vHG69kwh56ZBGbw/smhxtPM9s6BbSelal3VCnD2/8QNRyPOhqJdR4AJ6Rez26P0z/YByRwmteLIqwTNR69JqWgWdnwPynBUtklwuk4TLyJ6X4TteW5ibhGb1OEDkfXmTzYuS4RB2guKSJaDLV2thzMGVIWS2CuLbcWmJCCP79+WANTxY+cSISWaeYax4FE+UgxHRExec1MeJmfNOW6B4iWRxakRhGzfMq9gpO+DKInrhSS8jfkPgkdor0rP4gntYL1cTjzNGAm3nUQz/IBP0edGTY9FTcbslsmt/jz5Jc6TSahiL9Z/PMIw8qf10d6EAnyP+7wP21s4uxrC8VAn5UWVcpBlQd7JUagwkgOfWygtzrUPaKf5tj49ZR4TeCc2vNmgnfbRml/tY+jdiQCIVixGltUcNOPXNY/42S9dj/lQz0vqllh+MKW5chcJaXEpgUJAESCi9PdAkkWvMdbMyicLWAA526RdkLP9xAmA5yGc8pBoRwd+xMxXiu+mwAwAqeT8q1L34QnvpAJcA1HvDNysRPglQ=
  run:
  - heroku run rake db:create RAILS_ENV=production
  - heroku run rake db:migrate RAILS_ENV=production
  - heroku run rake assets:precompile
  app: rushabhsales
  on:
    repo: shalinbhatt/rushabhsales
env:
  global:
    secure: XarqyVlMLVpufIxOLLxrL6FJhII1P2HlE/FTiqg1jjYVbPX3PyDcTZjREaFXYwEniwZ3L/Ur7q/44cOGttU8pRzy9Vn27NQSmecrMFHS1MeDowQiRytOwU4mSUuVwSWgUFK9sKjWpJTlKSktlHPiMt0WM3Yb7kC2TYPBf2OwPKB4elsb1XQnG6FZXIAq6koecuUIpsyUlZSRt12+kQW3HyOjoxQ6P8loMoLP9JDZHKiTYeWMziEbfklevIcunIdQjekmMQarxDeSIpMjnZCOOi3ax1FzitEBTQs/zD4XiUvfdIpBnlYgD1pFd+2yC3PlfyLfBWpUponUWTyjDElfMp/HOzHmz5KIbdYGapZ09yy8gx1aiPxM3/jpR3KBrXxUlMOFCPNoWhvaeAeByhT9Ut4Pjb9of7ermkjDpeyIGg8UipNg9wsNQI20ELaIBq0Km/JGCxAqRub47J2PMzGvYH6eH1lGlA7g/TpyLEwYXs9iCF8/wn1EScnWj9kdAFIVaac4ocRfRbYn+J+Cd9i6iQA6uScygbWBHkMGcx8K/5BogIs4BJ5OeZFiXdrD9r2Pl/wEehRfy6gjbJJXbs3MutYYZOCx2kgkMWVc6zXQ0zUHX57JzJHAI3mhUxwyPoRJTRvC4b0UdqOI1bVIQoSOLLBdRL3PMkzFrtaFyVl8JrQ=
